version: '3'
services:
  frontend:
      build: ./frontend
      volumes:
        - ./frontend:/usr/src/app
        - ./ssr_dist:/usr/src/ssr_dist
      command: bash -c "npm install && ng build --prod && cp -r /usr/src/app/dist/upcoming-movies/* /usr/src/ssr_dist/"

  webapi:
    build: webapi/
    volumes:
       - ./ssr_dist:/app+/wwwroot
    depends_on:
      - 'frontend'
    command: bash -c "dotnet UpcomingMovies.Api.dll"
    environment:
    - PORT=80
    ports:
      - "80:80"